<a href="https://colab.research.google.com/github/likelamb/distance_measure/blob/main/distance_measure_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import open3d as o3d
import plotly.graph_objects as go

In [ ]:
def chamfer_distance(S1, S2):
    S1_expanded = np.expand_dims(S1, axis=1)
    S2_expanded = np.expand_dims(S2, axis=0)

    distances = np.linalg.norm(S1_expanded - S2_expanded, axis=-1)

    min_distances_S1_to_S2 = np.min(distances, axis=1)
    min_distances_S2_to_S1 = np.min(distances, axis=0)
    chamfer_dist = np.mean(min_distances_S1_to_S2) + np.mean(min_distances_S2_to_S1)
    return chamfer_dist

def point_cloud_similarity(S1, S2, method='chamfer'):
    """
    포인트 클라우드 유사도 계산 함수
    :param S1: 포인트 클라우드 S1, shape = [num_points, 3]
    :param S2: 포인트 클라우드 S2, shape = [num_points, 3]
    :param method: 유사도 계산 방법 ('chamfer' 또는 'emd')
    :return: 유사도 값
    """
    if method == 'chamfer':
        return chamfer_distance(S1, S2)
    else:
        raise ValueError("Unknown method: {}. Use 'chamfer' or 'emd'.".format(method))

In [ ]:
POINTNUM = 4096
points1 = np.random.rand(POINTNUM, 3)
colors1 = np.array([1.0,0.0,0.0] * POINTNUM).reshape(POINTNUM,-1)
print(colors1[:5])
print(colors1.shape)

points2 = np.random.rand(POINTNUM, 3)
colors2 = np.array([0.0,0.0,1.0] * POINTNUM).reshape(POINTNUM,-1)
print(colors2[:5])
print(colors2.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(4096, 3)
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(4096, 3)


In [ ]:
fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points1[:,0], y=points1[:,1], z=points1[:,2],
            mode='markers',
            marker=dict(size=1, color=colors1)
        ),
        go.Scatter3d(
            x=points2[:,0], y=points2[:,1], z=points2[:,2],
            mode='markers',
            marker=dict(size=1, color=colors2)
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()

In [ ]:
chamfer_dist = point_cloud_similarity(points1, points2, method='chamfer')
print("Chamfer Distance:", chamfer_dist)

Chamfer Distance: 0.07048248401619368


In [ ]:
from google.colab import drive
drive.mount('/content/Drive')

Drive already mounted at /content/Drive; to attempt to forcibly remount, call drive.mount("/content/Drive", force_remount=True).


In [ ]:
raw = np.loadtxt("/content/Drive/MyDrive/test_distance_measures/bunny.ply")
#raw[:,0] = raw[:,0] / np.max(raw[:,0])
#raw[:,1] = raw[:,1] / np.max(raw[:,1])
#raw[:,2] = raw[:,2] / np.max(raw[:,2])
print(raw.shape)
POINTNUM = raw.shape[0]
points1 = np.zeros_like(raw[:,:3])
points1[:,0] = ((raw[:,0] - np.mean(raw[:,0])) / np.std(raw[:,0]))
points1[:,1] = ((raw[:,1] - np.mean(raw[:,1])) / np.std(raw[:,1]))
points1[:,2] = ((raw[:,2] - np.mean(raw[:,2])) / np.std(raw[:,2]))
colors1 = np.array([1.0,0.0,0.0] * POINTNUM).reshape(POINTNUM,-1)
print(points1[:5])
print(colors1[:5])
print(points1.shape, colors1.shape)

points2 = np.zeros_like(raw[:,:3])
points2[:,0] = np.random.uniform(np.min(points1[:,0]), np.max(points1[:,0]), POINTNUM)
points2[:,1] = np.random.uniform(np.min(points1[:,1]), np.max(points1[:,1]), POINTNUM)
points2[:,2] = np.random.uniform(np.min(points1[:,2]), np.max(points1[:,2]), POINTNUM)

points2 = np.copy(points1)
noise = np.random.rand(points2.shape[0],points2.shape[1])-0.5
points2[:2000] = points1[:2000] + noise[:2000]*0.9

colors2 = np.array([0.0,0.0,1.0] * POINTNUM).reshape(POINTNUM,-1)
print(points2[:5])
print(colors2[:5])
print(points2.shape, colors2.shape)

fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points1[:,0], y=points1[:,1], z=points1[:,2],
            mode='markers',
            marker=dict(size=1, color=colors1)
        ),
        go.Scatter3d(
            x=points2[:,0], y=points2[:,1], z=points2[:,2],
            mode='markers',
            marker=dict(size=1, color=colors2)
        )
    ],
    layout=dict(
        scene=dict(
            xaxis=dict(visible=False),
            yaxis=dict(visible=False),
            zaxis=dict(visible=False)
        )
    )
)
fig.show()

chamfer_dist = point_cloud_similarity(points1, points2, method='chamfer')
print("Chamfer Distance:", chamfer_dist)

(8171, 5)
[[-0.24933988  0.78760922 -0.15154282]
 [-0.4572409   0.81427888 -0.2690145 ]
 [-1.03637185  1.35283094  1.00712702]
 [ 0.61916404  0.85221275  0.47635502]
 [ 0.11584066  0.76756556 -0.04424244]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(8171, 3) (8171, 3)
[[-0.54167544  0.70602455 -0.60006139]
 [-0.26203244  1.06201767 -0.03749901]
 [-0.90918437  0.9780964   0.90708698]
 [ 0.4119416   0.90565011  0.6316668 ]
 [ 0.24915545  0.3462151  -0.22430855]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(8171, 3) (8171, 3)


Chamfer Distance: 0.0677888053925993
